services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # live code reloading (dev only)
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    ports:
      - "3000:80"